<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Saurabhs-MacBook-Pro.local" name="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm" tests="11" failures="0" timestamp="1 Dec 2020 17:15:53 GMT" time="4.021" errors="1">
  <testcase name="testInValidCustomerDetails" time="0.102" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="1.821" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm">
    <error type="java.lang.AssertionError" message="Test Case TestCase_1is being executed. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Case TestCase_1is being executed. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm.testInValidCustomerDetails(TestCustomerForm.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testInValidCustomerDetails -->
  <testcase name="testInValidCustomerDetails" time="0.321" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="0.189" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="0.175" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="0.231" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="0.262" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="0.233" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="0.375" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="0.149" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
  <testcase name="testInValidCustomerDetails" time="0.163" classname="test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm"/>
</testsuite> <!-- test.java.CustomerRagistration.CustomerRagistration.TestCustomerForm -->
